### ISSUE TITLE
Installation guide for pipenv environment

### ISSUE THREAD

**Issue by owl-uccs** [fredzzhang/pocket#49]
Please add installation guide for `pipenv `  environment. I am not using conda environment.

**Comment by fredzzhang** [comment]
Regardless of the package management software you use, just install Python 3.8 and the following dependencies with the latest version:
```
pickle
pytorch
torchvision
matplotlib
tqdm
scipy
```
Afterwards, make sure to add the root directory of the library (`pocket/`) to your `PYTHONPATH`. You should be good to go.

Fred.

**Comment by owl-uccs** [comment]
Thanks. It works.
