### ISSUE TITLE
ModuleNotFoundError: No module named 'conda_build'

### ISSUE THREAD

**Issue by hangzhiyiwei** [fredzzhang/pocket#60]
Hi, I am trying to set up the pocket environment. I have used python 3.8 to create a virtual environment, but this error occurs

Traceback (most recent call last):
  File "/home/hzyw/anaconda3/bin/conda-develop", line 7, in <module>
    from conda_build.cli.main_develop import main
ModuleNotFoundError: No module named 'conda_build'

Even when I downgrade the python to 3.7, the problem occurs again. I am really confused.

**Comment by hangzhiyiwei** [comment]
> 

Hi @fredzzhang.

Actually I have created a new environment following the instructions. But when I run the command "conda develop pocket", the above error occurs. 

(pocket) $  conda develop pocket
Traceback (most recent call last):
  File "/home/hzyw/anaconda3/bin/conda-develop", line 7, in <module>
    from conda_build.cli.main_develop import main
ModuleNotFoundError: No module named 'conda_build'

Thanks very much.

**Comment by fredzzhang** [comment]
Hi @hangzhiyiwei,

Can you check whether `conda_build` is installed properly by running `conda list | grep conda-build`?

Fred.

**Comment by hangzhiyiwei** [comment]
> 

Hi @fredzzhang ,

Thanks. Here is the result.
$ conda list | grep conda-build
conda-build               3.22.0           py38h578d9bd_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

**Comment by fredzzhang** [comment]
Hmm...that's odd. It seems everything is installed correctly. Can you try `pip install conda-build` instead and see if it works?

**Comment by hangzhiyiwei** [comment]
Actually, I have a question. The error occurs in file /home/hzyw/anaconda3/bin/conda-develop, but I think the conda-develop file should be selected in the virtual environment, that is  /home/hzyw/anaconda3/envs/pocket/bin, right?

**Comment by fredzzhang** [comment]
Yes. Have you activated the environment with `conda activate pocket`?

**Comment by hangzhiyiwei** [comment]
Yes, I have activated. So I am confused. How can I use the virtual environment conda-develop?

**Comment by fredzzhang** [comment]
That might just be a problem with `conda-build` then.

The point of running `conda develop pocket` is to add the library to your system path for Python, so that you can invoke the library anywhere on your machine. There are many other ways to do this. You can try adding the path of `pocket` to your `PYTHONPATH` by adding the following line into your `.bashrc`.

```
export PYTHONPATH="${PYTHONPATH}:/your/path/to/pocket"
```

Afterwards, either start a new terminal or run `source ~/.bashrc` to update the current terminal. This should allow you to do the same thing as `conda develop pocket`. To check if it is successful, go to a random location on your machine and start a python shell. Try `import pocket` and `import pocket.core` to see if you can access the library.

Fred.

**Comment by hangzhiyiwei** [comment]
Hi @fredzzhang,

I have added the following line into my .bashrc file.

export PYTHONPATH="${PYTHONPATH}:/home/hzyw/anaconda3/envs/pocket"

However, after $ source ~/.bashrc, it cannot find pocket library

(pocket) ~$ python 
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pocket'

**Comment by fredzzhang** [comment]
The path of pocket is meant to be where you cloned the repository, not the conda environment.

**Comment by hangzhiyiwei** [comment]
Oh, I am sorry.
It works with your guidance! Thanks very much!
