### ISSUE TITLE
transformerDecoder

### ISSUE THREAD

**Issue by soberguo** [fredzzhang/pocket#64]
Hello,fredzzhang,thank you very much for providing this repository. I think it is very helpful for hoi detection tasks and is very convenient to use. However, during use, I found that there is only encoder and no decoder in the transformer.py file.I hope you can improve it in your spare time. Thank you very much for your help.

**Comment by fredzzhang** [comment]
Hi @soberguo,

I didn't include the decoder  in this library because its implementation could vary depending on the task. You can find an implementation in the PViC codebase [here](https://github.com/fredzzhang/pvic/blob/main/transformers.py).

Fred.
